version: "2"

services:
  web:
    image: hautvfami/ipa-server:v1.0
    container_name: ipa-server
    restart: unless-stopped
    environment:
      # server public url
      - PUBLIC_URL=
      # option, remote storager config, s3://ENDPOINT:AK:SK:BUCKET, alioss://ENDPOINT:AK:SK:BUCKET, qiniu://[ZONE]:AK:SK:BUCKET
      - REMOTE=
      # option, remote storager public url, https://cdn.example.com
      - REMOTE_URL=
      # option, metadata storage path, use random secret path to keep your metadata safer in case of remote storage
      - META_PATH=storage.json
      # delete app enabled, true/false
      - DELETE_ENABLED=true
    ports:
      - "27668:8080"
    # volumes:
    #   - "/home/app-store.vuihoc.vn/upload:/app/upload"
